name: SonarCloud Scan with Parameters
on:
  workflow_dispatch:  # Manual trigger
  repository_dispatch:  # Triggered via API (scripts1.py)
    types: [sonar_cloud_scan_github_actions]

jobs:
  RunSonarCloudAnalysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Required for SonarCloud analysis

      - name: Print Parameters (if triggered via API)
        if: github.event_name == 'repository_dispatch'
        run: |
          echo "Parameter 1: ${{ github.event.client_payload.parameter1 || 'Not provided' }}"
          echo "Parameter 2: ${{ github.event.client_payload.parameter2 || 'Not provided' }}"

      - name: Set up JDK (if Java project)
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # For PR decoration
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}    # From SonarCloud
        with:
          args: >
            -Dsonar.organization=ramsnow42key
            -Dsonar.projectKey=ramsnow42key_SonarCloudCodeAnalyisis
            -Dsonar.python.coverage.reportPaths=coverage.xml
            -Dsonar.projectVersion=${{ github.run_id }}
            -Dsonar.analysis.param1=${{ github.event.client_payload.parameter1 || '' }}
            -Dsonar.analysis.param2=${{ github.event.client_payload.parameter2 || '' }}